import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolveFurnaceFrameLayout } from '../src/xr/furnace/drawVrFurnaceFrame.js';
import { resolveProcessTelemetry, shouldRefreshTelemetry } from '../src/xr/furnace/vrFurnaceTelemetry.js';
import { ASTRO_FURNACE_PANEL_SCREENS, ASTRO_FURNACE_PANEL_STATES, asterionPreviewAnimationActive, wireframeDissolveVisible } from '../src/xr/furnace/createVrAstroFurnacePanel.js';
import { createVrAstroFurnaceProcessSource } from '../src/xr/furnace/createVrAstroFurnaceProcessSource.js';

const wide = resolveFurnaceFrameLayout({ width: 400, height: 100, cornerSize: 28 });
const tall = resolveFurnaceFrameLayout({ width: 100, height: 400, cornerSize: 28 });
assert.equal(wide.cornerSize, tall.cornerSize); assert.equal(wide.horizontalLength, 344); assert.equal(tall.verticalLength, 344);
const tiny = resolveFurnaceFrameLayout({ width: 12, height: 8, cornerSize: 28 });
assert.ok(tiny.horizontalLength >= 0 && tiny.verticalLength >= 0);

for (const phase of ['IDLE', 'PRESSING', 'SPINUP', 'STEADY', 'EXTRACTION', 'COOLDOWN']) {
  const telemetry = resolveProcessTelemetry({ state: phase, overallProgress: .5, extractionProgress: .5, angularSpeed: 2 });
  assert.equal(telemetry.phase, phase);
}
assert.equal(resolveProcessTelemetry({ state: 'IDLE', completed: true }).phase, 'COMPLETE');
const idle = resolveProcessTelemetry({ state: 'IDLE', overallProgress: 1, extractionProgress: 1 });
assert.equal(idle.showProgress, false); assert.equal(idle.overallProgress, 0); assert.match(idle.label, /OCZEKIWANIE/);
const openInserted = resolveProcessTelemetry({ state: 'IDLE', contentState: 'INSERTED', chamberState: 'OPEN' });
assert.equal(openInserted.showProgress, false); assert.match(openInserted.label, /ZAMKNIJ POKRYWĘ\nI ROZPOCZNIJ EKSTRAKCJĘ/);
const closedInserted = resolveProcessTelemetry({ state: 'IDLE', contentState: 'INSERTED', chamberState: 'CLOSED' });
assert.equal(closedInserted.showProgress, false); assert.equal(closedInserted.label, 'GOTOWY DO EKSTRAKCJI');
const active = resolveProcessTelemetry({ state: 'EXTRACTION', overallProgress: .6, extractionProgress: .5 });
assert.equal(active.showProgress, true); assert.equal(active.extractionProgress, .5); assert.equal(active.silhouetteOpacity, 1);
const complete = resolveProcessTelemetry({ state: 'COMPLETE', overallProgress: 1, extractionProgress: 1 });
assert.equal(complete.silhouetteOpacity, 0); assert.match(complete.label, /PAMIĘCI PIECA/);
assert.equal(shouldRefreshTelemetry({ active: false, elapsed: 10, lastRedraw: 0 }), false);
assert.equal(shouldRefreshTelemetry({ active: true, elapsed: .084, lastRedraw: 0, refreshHz: 12 }), true);
assert.equal(shouldRefreshTelemetry({ active: true, elapsed: .02, lastRedraw: 0, refreshHz: 12 }), false);
assert.equal(asterionPreviewAnimationActive({ panelState: ASTRO_FURNACE_PANEL_STATES.VISIBLE, screen: ASTRO_FURNACE_PANEL_SCREENS.ASTERION_SPHERE }), true);
assert.equal(shouldRefreshTelemetry({ active: asterionPreviewAnimationActive({ panelState: ASTRO_FURNACE_PANEL_STATES.VISIBLE, screen: ASTRO_FURNACE_PANEL_SCREENS.ASTERION_SPHERE }), elapsed: .084, lastRedraw: 0, refreshHz: 12 }), true);
assert.equal(asterionPreviewAnimationActive({ panelState: ASTRO_FURNACE_PANEL_STATES.HIDDEN, screen: ASTRO_FURNACE_PANEL_SCREENS.ASTERION_SPHERE }), false);
assert.equal(shouldRefreshTelemetry({ active: asterionPreviewAnimationActive({ panelState: ASTRO_FURNACE_PANEL_STATES.HIDDEN, screen: ASTRO_FURNACE_PANEL_SCREENS.ASTERION_SPHERE }), elapsed: 1, lastRedraw: 0, refreshHz: 12 }), false);
let interaction;
const runtimeProcessSource = createVrAstroFurnaceProcessSource(() => interaction);
assert.equal(typeof runtimeProcessSource.getExtractionProgress, 'function');
assert.equal(runtimeProcessSource.getExtractionProgress(), 0);
interaction = { getState: () => 'EXTRACTION', getProgress: () => .75, getExtractionProgress: () => .5, getAngularSpeed: () => 2, getProcessAngle: () => 1 };
assert.equal(runtimeProcessSource.getExtractionProgress(), .5);
assert.equal(resolveProcessTelemetry({ state: runtimeProcessSource.getState(), overallProgress: runtimeProcessSource.getProgress(), extractionProgress: runtimeProcessSource.getExtractionProgress() }).extractionProgress, .5);
const panelSource = readFileSync(new URL('../src/xr/furnace/createVrAstroFurnacePanel.js', import.meta.url), 'utf8');
const experienceSource = readFileSync(new URL('../src/experienceVr.js', import.meta.url), 'utf8');
assert.match(experienceSource, /processSource: createVrAstroFurnaceProcessSource\(\(\) => astroFurnaceActivateInteraction\)/);
assert.doesNotMatch(panelSource, /resolveAsciiFrame|PROCESS_ASCII|buildProgressBar/);
assert.match(panelSource, /drawAsterionPreview/); assert.doesNotMatch(panelSource, /context\.ellipse/);
assert.equal(panelSource.match(/context\.arc/g)?.length, 1);
assert.match(panelSource, /patchGeometryByAssetId/); assert.match(panelSource, /patch\.segments2d\.forEach/);
assert.match(panelSource, /spherePatchVisualScaleMultiplier: 1\.10/);
assert.match(panelSource, /states\[id\]\?\.committed/); assert.doesNotMatch(panelSource, /segment < progress\.absorbed/);
assert.match(panelSource, /getInsertedShellWireframe/); assert.doesNotMatch(panelSource, /for \(let ring = 0; ring < 4/);
const ordered = Array.from({ length: 101 }, (_, index) => ({ dissolveOrder: index / 100 }));
assert.equal(ordered.filter((segment) => wireframeDissolveVisible(segment, 0)).length, 101);
assert.equal(ordered.filter((segment) => wireframeDissolveVisible(segment, .5)).length, 51);
assert.equal(ordered.filter((segment) => wireframeDissolveVisible(segment, 1)).length, 0);
assert.match(panelSource, /\['COOLDOWN', 'COMPLETE'\]\.includes\(telemetry\.phase\)/);
assert.match(panelSource, /telemetry\.phase === 'EXTRACTION' \? telemetry\.extractionProgress : 0/);
for (const phase of ['SPINUP', 'STEADY', 'COOLDOWN']) assert.equal(resolveProcessTelemetry({ state: phase, extractionProgress: phase === 'COOLDOWN' ? 1 : 0 }).showProgress, false);
assert.match(panelSource, /VrAstroFurnacePanelFrontPlane/);
assert.match(panelSource, /VrAstroFurnacePanelBackPlane/);
assert.equal(panelSource.match(/new THREE\.PlaneGeometry/g)?.length, 2);
assert.equal(panelSource.match(/new THREE\.CanvasTexture/g)?.length, 1);
assert.match(panelSource, /const renderPlanes = \[frontPlane, backPlane\]/);
assert.match(panelSource, /backPlane\.rotation\.y = Math\.PI/);
assert.match(panelSource, /map: texture, side: THREE\.FrontSide/);
assert.doesNotMatch(panelSource, /THREE\.DoubleSide/);
assert.match(panelSource, /raycaster\.intersectObjects\(renderPlanes, false\)/);
console.log('VR furnace panel visual helper tests passed.');
