import assert from 'node:assert/strict';
import * as THREE from '../src/vendor/three.js';
import { createVrGlyphInteraction } from '../src/xr/createVrGlyphInteraction.js';
import { ExperienceDirector } from '../src/xr/progression/ExperienceDirector.js';
import { createVrProgressionController } from '../src/xr/progression/createVrProgressionController.js';
import { stateAtVrScenarioPoint } from '../src/xr/progression/reconstructVrScenarioState.js';
import { experienceVrPages } from '../src/content/experienceVrPages.js';
import { VR_SCENARIO_CAPABILITY, vrExperienceScenario } from '../src/xr/progression/vrExperienceScenario.js';

const controllers = [new THREE.Group(), new THREE.Group()];
const records = controllers.map((controller, index) => ({ index, controller, handedness: index ? 'right' : 'left', isConnected: true, currentHit: null, currentRayLength: 4 }));
const glyph = new THREE.Group();
const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.5, 0.5), new THREE.MeshBasicMaterial()); mesh.position.z = -2; glyph.add(mesh);
const hiddenMesh = new THREE.Mesh(new THREE.SphereGeometry(0.2), new THREE.MeshBasicMaterial()); hiddenMesh.visible = false; glyph.add(hiddenMesh);
const hiddenByParent = new THREE.Group(); hiddenByParent.visible = false;
hiddenByParent.add(new THREE.Mesh(new THREE.BoxGeometry(1, 1, 1), new THREE.MeshBasicMaterial())); glyph.add(hiddenByParent);
let completions = 0;
const interaction = createVrGlyphInteraction({ controllers: records, nodes: [glyph], settings: { holdDurationSeconds: 0.5, holdLostGraceSeconds: 0.15 }, onGlyphHoldComplete: ({ node }) => { assert.equal(node, glyph); completions += 1; } });
glyph.updateMatrixWorld(true); interaction.update();
assert.equal(interaction.targets[0].halo.visible, true, 'an actionable ray target shows its halo');
assert.ok(interaction.targets[0].halo.shells.every(({ visible }) => visible));
assert.equal(interaction.targets[0].halo.shells.length, 1, 'halo excludes directly and effectively hidden meshes');
assert.equal(interaction.targets[0].halo.material.isShaderMaterial, true, 'halo uses screen-space shader material');
assert.equal(interaction.targets[0].halo.material.uniforms.thicknessPixels.value, 3);
controllers[0].dispatchEvent({ type: 'selectstart' });
interaction.update(0.49); assert.equal(completions, 0);
interaction.update(0.01); assert.equal(completions, 1);
interaction.update(2); assert.equal(completions, 1, 'one selectstart completes exactly once');
controllers[0].dispatchEvent({ type: 'selectend' }); controllers[0].dispatchEvent({ type: 'selectstart' });
interaction.update(0.2); controllers[0].rotation.y = Math.PI; interaction.update(0.1); controllers[0].rotation.y = 0; interaction.update(0.31);
assert.equal(completions, 2, 'target loss shorter than grace preserves accumulated hold');
controllers[0].dispatchEvent({ type: 'selectend' }); controllers[0].dispatchEvent({ type: 'selectstart' });
interaction.update(0.2); controllers[0].rotation.y = Math.PI; interaction.update(0.16); controllers[0].rotation.y = 0; interaction.update(1);
assert.equal(completions, 2, 'target loss longer than grace resets hold');
controllers[0].dispatchEvent({ type: 'selectstart' }); interaction.update(0.2); controllers[0].dispatchEvent({ type: 'selectend' }); interaction.update(1); assert.equal(completions, 2, 'selectend cancels immediately');
controllers[0].dispatchEvent({ type: 'selectstart' }); controllers[1].dispatchEvent({ type: 'selectstart' }); interaction.update(0.5); assert.equal(completions, 4, 'controllers hold independently');
interaction.reset(); assert.equal(interaction.holds.size, 0); assert.ok(records.every(({ currentHit }) => currentHit === null));
assert.equal(interaction.targets[0].halo.visible, false, 'reset clears target halo');
const haloMaterial = interaction.targets[0].halo.material;
let haloDisposed = false; haloMaterial.addEventListener('dispose', () => { haloDisposed = true; });
interaction.dispose();
assert.equal(haloDisposed, true, 'dispose releases the halo material');
assert.equal(mesh.children.length, 0, 'dispose removes the shared-geometry halo shell');

const secondCycleProgression = createVrProgressionController({ pages: experienceVrPages });
secondCycleProgression.hydrateScenarioState(stateAtVrScenarioPoint(vrExperienceScenario, '4.10').progression);
const secondCycleDirector = new ExperienceDirector({ scenario: vrExperienceScenario, startPointId: '4.10' });
assert.equal(secondCycleDirector.can(VR_SCENARIO_CAPABILITY.CAN_USE_GLYPHS), true);
const tierTwoPage = secondCycleProgression.getNextPage('ethics-life-protection', 2);
assert.equal(tierTwoPage?.order, 2, 'authored capability plus Tier 1 persistent state exposes the next tier');
console.log('VR glyph interaction assertions passed');
