import assert from 'node:assert/strict';
import * as THREE from '../src/vendor/three.js';
import { createVrGlyphInteraction } from '../src/xr/createVrGlyphInteraction.js';

const controllers = [new THREE.Group(), new THREE.Group()];
const records = controllers.map((controller, index) => ({ index, controller, handedness: index ? 'right' : 'left', isConnected: true, currentHit: null, currentRayLength: 4 }));
const glyphA = new THREE.Group();
const nested = new THREE.Group();
const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.5, 0.5), new THREE.MeshBasicMaterial());
mesh.position.z = -2; nested.add(mesh); glyphA.add(nested);
const glyphB = new THREE.Group();
glyphB.position.x = 2;
let activation = null;
const interaction = createVrGlyphInteraction({ controllers: records, nodes: [glyphA, glyphB], onEntryGlyphActivated: ({ node }) => { activation = node; } });
assert.equal(interaction.targets[0].fallbackCollider, null);
assert.equal(interaction.targets[1].fallbackCollider.parent, glyphB);
glyphA.updateMatrixWorld(true); glyphB.updateMatrixWorld(true);
interaction.update();
assert.equal(records[0].currentHit, glyphA);
assert.equal(records[1].currentHit, glyphA);
assert.equal(interaction.hoveredGlyphs.size, 1);
interaction.setEntryReady(glyphB);
controllers[0].dispatchEvent({ type: 'selectstart' });
assert.equal(activation, null);
interaction.setEntryReady(glyphA);
controllers[0].dispatchEvent({ type: 'selectstart' });
assert.equal(activation, glyphA);
controllers[0].dispatchEvent({ type: 'selectstart' });
assert.equal(interaction.activatedEntryGlyph, glyphA);
controllers[1].rotation.y = Math.PI; interaction.update();
assert.equal(records[0].currentHit, glyphA); assert.equal(records[1].currentHit, null);
interaction.reset(); assert.ok(records.every(({ currentHit }) => currentHit === null));
interaction.dispose(); interaction.dispose();
assert.equal(interaction.targets.length, 0);
console.log('VR glyph interaction assertions passed');
