import assert from 'node:assert/strict';
import * as THREE from '../src/vendor/three.js';
import { createVrGlyphInteraction } from '../src/xr/createVrGlyphInteraction.js';

const controllers = [new THREE.Group(), new THREE.Group()];
const records = controllers.map((controller, index) => ({ index, controller, handedness: index ? 'right' : 'left', isConnected: true, currentHit: null, currentRayLength: 4 }));
const glyph = new THREE.Group();
const mesh = new THREE.Mesh(new THREE.BoxGeometry(0.5, 0.5, 0.5), new THREE.MeshBasicMaterial()); mesh.position.z = -2; glyph.add(mesh);
let completions = 0;
const interaction = createVrGlyphInteraction({ controllers: records, nodes: [glyph], settings: { holdDurationSeconds: 0.5 }, onGlyphHoldComplete: ({ node }) => { assert.equal(node, glyph); completions += 1; } });
glyph.updateMatrixWorld(true); interaction.update();
controllers[0].dispatchEvent({ type: 'selectstart' });
interaction.update(0.49); assert.equal(completions, 0);
interaction.update(0.01); assert.equal(completions, 1);
interaction.update(2); assert.equal(completions, 1, 'one selectstart completes exactly once');
controllers[0].dispatchEvent({ type: 'selectend' }); controllers[0].dispatchEvent({ type: 'selectstart' });
controllers[0].rotation.y = Math.PI; interaction.update(0.25); controllers[0].rotation.y = 0; interaction.update(1); assert.equal(completions, 1, 'lost targeting cancels');
controllers[0].dispatchEvent({ type: 'selectstart' }); interaction.update(0.2); controllers[0].dispatchEvent({ type: 'selectend' }); interaction.update(1); assert.equal(completions, 1, 'selectend cancels');
controllers[0].dispatchEvent({ type: 'selectstart' }); controllers[1].dispatchEvent({ type: 'selectstart' }); interaction.update(0.5); assert.equal(completions, 3, 'controllers hold independently');
interaction.reset(); assert.equal(interaction.holds.size, 0); assert.ok(records.every(({ currentHit }) => currentHit === null));
interaction.dispose();
console.log('VR glyph interaction assertions passed');
