import assert from 'node:assert/strict';
import * as THREE from '../src/vendor/three.js';
import { createVrIntroSequence, VR_INTRO_COPY, VR_INTRO_STATE } from '../src/xr/guidance/createVrIntroSequence.js';

function fixture({ bypass = false, onReliquaryReveal = () => {} } = {}) {
  const platformRoot = new THREE.Group(); const progressFloor = { object: new THREE.Group() }; progressFloor.object.add(platformRoot);
  const monkeyMotionRoot = new THREE.Group(); monkeyMotionRoot.position.set(0, 1.25, -0.5); progressFloor.object.add(monkeyMotionRoot);
  const playerRig = new THREE.Group(); const head = new THREE.Vector3(0, 1.7, 20);
  const glyphRing = new THREE.Group(); const platformFixturesRoot = new THREE.Group(); const sector = new THREE.Group(); sector.userData.branchId = 'x'; progressFloor.object.add(sector);
  const monkeyStoneRoot = new THREE.Group(); progressFloor.object.add(monkeyStoneRoot);
  let message = ''; let override = null; let radius = 4; let attention = 0; let rays = 0; let revealComplete = 0; let silenceComplete = 0; let playerOpenedGuide = 0; let playerViewedControls = 0; let playerClosedGuide = 0; let monkeyHovered = 0; let monkeyTriggered = 0; let monkeyReachedThreshold = 0; let playerEnteredRing = 0; let monkeySettled = 0; let glyphHintTimeout = 0; const invitationChoices = []; const followPauseChanges = []; const thresholdChoices = []; let interactionEnables = 0; let endSessions = 0;
  const panel = { open: false, view: 'MENU', section: null, isOpen() { return this.open; }, getViewState() { return this.view; }, getActiveSectionId() { return this.section; } };
  const fog = { progress: 0, radius: 20, setRadiusCalls: 0, installed: true, active: false, restart() { this.progress = 0; this.radius = 20; this.setRadiusCalls = 0; this.installed = true; this.active = false; }, start() { this.active = true; }, update(d) { if (!this.active) return; this.progress = Math.min(1, this.progress + d / 10); this.radius = 20 - 3 * this.progress; if (this.progress >= 1) this.active = false; }, setRadius(v) { this.radius = v; this.setRadiusCalls += 1; }, dispose() { this.installed = false; }, skipToEnd() { this.progress = 1; this.radius = 0; this.installed = false; }, getSnapshot() { return { progress: this.progress, radius: this.radius, installed: this.installed }; } };
  const monkeyGuide = { showMessage(v) { message = v; return { lineCount: v ? 1 : 0 }; }, setDialogueOverride(v) { override = v; }, setInteractionEnabled(value) { if (value) interactionEnables += 1; }, notifyAttention() { attention += 1; } };
  const locomotion = { reset() { radius = 4; }, setWalkRadius(v, options) { radius = v; this.lastOptions = options; } };
  const settings = { enabled: true, locale: 'en', introRevealDuration: 10, postRevealSilenceDuration: 2, insideSafeMargin: .75, glyphFreeExploreDuration: 60, guideSpeed: 2, guideTurnDuration: 1, followGraceDistance: 3, pauseDistance: 3.2, resumeDistance: 2.4, revealProgress: .72, messageDisplayDuration: 0, messageGapDuration: 0, questionGapDuration: 0 };
  const spatial = { entryDirection: { x: 0, y: 0, z: 1 }, playerStartRadius: 20, monkeyStartRadius: 18, monkeyFinal: { x: 0, y: 0, z: 0 }, ringRadius: 7.6, thresholdOutsideDistance: 1 };
  const sequence = createVrIntroSequence({ monkeyGuide, monkeyMotionRoot, monkeyVisualRoot: new THREE.Group(), monkeyStoneRoot, platformRoot, playerRig, playerGuidePanel: panel, fogReveal: fog, glyphRing, progressFloor, platformFixturesRoot, locomotion, spatial, settings, getHeadPosition: () => head.clone(), onOpeningRaysReady: () => { rays += 1; }, onIntroRevealComplete: () => { revealComplete += 1; }, onPostRevealSilenceComplete: () => { silenceComplete += 1; }, onPlayerOpenedGuide: () => { playerOpenedGuide += 1; }, onPlayerViewedControls: () => { playerViewedControls += 1; }, onPlayerClosedGuide: () => { playerClosedGuide += 1; }, onMonkeyHovered: () => { monkeyHovered += 1; }, onMonkeyTriggered: () => { monkeyTriggered += 1; }, onInvitationSelected: (choice) => { invitationChoices.push(choice); }, onFollowPauseChanged: (paused) => { followPauseChanges.push(paused); }, onMonkeyReachedThreshold: () => { monkeyReachedThreshold += 1; }, onThresholdSelected: (choice) => { thresholdChoices.push(choice); }, onPlayerEnteredRing: () => { playerEnteredRing += 1; }, onMonkeySettled: () => { monkeySettled += 1; }, onGlyphHintTimeout: () => { glyphHintTimeout += 1; }, onEndSession: () => { endSessions += 1; }, onReliquaryReveal, bypass });
  return { sequence, monkeyMotionRoot, monkeyStoneRoot, glyphRing, head, panel, fog, locomotion, getMessage: () => message, getOverride: () => override, getRadius: () => radius, getAttention: () => attention, getRays: () => rays, getRevealComplete: () => revealComplete, getSilenceComplete: () => silenceComplete, getPlayerOpenedGuide: () => playerOpenedGuide, getPlayerViewedControls: () => playerViewedControls, getPlayerClosedGuide: () => playerClosedGuide, getMonkeyHovered: () => monkeyHovered, getMonkeyTriggered: () => monkeyTriggered, getMonkeyReachedThreshold: () => monkeyReachedThreshold, getPlayerEnteredRing: () => playerEnteredRing, getMonkeySettled: () => monkeySettled, getGlyphHintTimeout: () => glyphHintTimeout, getInvitationChoices: () => invitationChoices, getFollowPauseChanges: () => followPauseChanges, getThresholdChoices: () => thresholdChoices, getInteractionEnables: () => interactionEnables, getEndSessions: () => endSessions };
}
function reachThreshold(value) {
  value.sequence.beginAfterXrCalibration(); value.sequence.update(10); assert.equal(value.sequence.beginPostRevealSilence(), true); value.sequence.update(2); assert.equal(value.sequence.beginControllerOnboarding(), true);
  for (let i = 0; i < 10; i += 1) value.sequence.update(.01);
  value.panel.open = true; value.sequence.update(0); assert.equal(value.sequence.continueControllerOnboarding(), true); value.panel.section = 'controls'; value.panel.view = 'DETAIL'; value.sequence.update(0);
  assert.equal(value.sequence.continueControllerOnboarding(), true);
  value.panel.open = false; value.sequence.update(0); assert.equal(value.sequence.continueControllerOnboarding(), true); for (let i = 0; i < 10; i += 1) value.sequence.update(.01);
  value.getOverride().onMonkeyHover(); assert.equal(value.sequence.continueControllerOnboarding(), true); value.getOverride().onMonkeyPress(); assert.equal(value.sequence.continueControllerOnboarding(), true); for (let i = 0; i < 8; i += 1) value.sequence.update(.01);
  value.getOverride().onSelect('go'); assert.equal(value.sequence.continueInvitation(1), true);
  for (let i = 0; i < 30 && value.sequence.getState() === VR_INTRO_STATE.FOLLOWING; i += 1) {
    value.head.copy(value.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())); value.sequence.update(.5);
  }
  assert.equal(value.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_MONKEY_REACHED_THRESHOLD);
  assert.equal(value.sequence.presentThresholdChoice(), true);
  assert.equal(value.sequence.getState(), VR_INTRO_STATE.THRESHOLD);
  for (let i = 0; i < 12 && typeof value.getOverride()?.onSelect !== 'function'; i += 1) value.sequence.update(.01);
}
function reachGlyphExplore(value) {
  reachThreshold(value);
  value.getOverride().onSelect('cross'); assert.equal(value.sequence.continueThresholdChoice(1), true); value.head.set(0, 1.7, 6.8);
  for (let i = 0; i < 30 && (!value.sequence.getDebugSnapshot().playerEnteredRing || !value.sequence.getDebugSnapshot().monkeySettled); i += 1) value.sequence.update(.25);
  assert.equal(value.sequence.getState(), VR_INTRO_STATE.MONKEY_SETTLING, 'actor waits for Runtime after emitting both facts');
  assert.equal(value.sequence.beginGlyphFreeExplore(), true);
  assert.equal(value.sequence.beginGlyphFreeExplore(), false, 'free-explore continuation is accepted exactly once');
}
assert.deepEqual(VR_INTRO_COPY.pl.opening, ['Dobrze.', 'Masz ręce.', 'Sprawdźmy tylko, gdzie co masz.']);
assert.equal(VR_INTRO_COPY.pl.panelPrompt, 'Naciśnij Y, żeby wejść do menu.');
assert.equal(VR_INTRO_COPY.en.panelPrompt, 'Press Y to open the menu.');
const f = fixture(); assert.equal(f.sequence.getState(), VR_INTRO_STATE.XR_CALIBRATING);
assert.equal(f.sequence.continueControllerOnboarding(), false, 'runtime continuation rejects the wrong actor state');
assert.equal(f.monkeyStoneRoot.visible, true); assert.equal(f.glyphRing.visible, true); assert.equal(f.fog.radius, 20);
f.sequence.beginAfterXrCalibration();
assert.ok(Math.abs(f.sequence.getDebugSnapshot().monkeyRadius - 18) < 1e-6);
f.head.x = 5; f.sequence.reset(); f.sequence.beginAfterXrCalibration();
assert.ok(Math.abs(f.sequence.getDebugSnapshot().monkeyRadius - 18) < 1e-6, 'physical head offset never changes Monkey start');
f.head.x = 0;
f.sequence.update(5); assert.equal(f.sequence.getState(), VR_INTRO_STATE.FOG_REVEAL); assert.equal(f.fog.radius, 18.5);
f.sequence.update(5); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_REVEAL); assert.equal(f.fog.radius, 17); assert.equal(f.getMessage(), '');
assert.equal(f.getRevealComplete(), 1, 'fog completion emits exactly once');
f.sequence.update(100); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_REVEAL, 'silence does not begin without Runtime');
assert.equal(f.getRevealComplete(), 1, 'waiting updates do not emit completion again');
assert.equal(f.sequence.beginControllerOnboarding(), false, 'onboarding cannot begin before silence completion');
assert.equal(f.sequence.beginPostRevealSilence(), true); assert.equal(f.sequence.beginPostRevealSilence(), false);
f.sequence.update(1.99); assert.equal(f.getMessage(), ''); assert.equal(f.getSilenceComplete(), 0);
f.sequence.update(.01); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_POST_REVEAL_SILENCE);
assert.equal(f.getSilenceComplete(), 1); assert.equal(f.getMessage(), ''); assert.equal(f.getRays(), 0); assert.equal(f.getInteractionEnables(), 0);
for (let i = 0; i < 20; i += 1) f.sequence.update(100);
assert.equal(f.getSilenceComplete(), 1, 'waiting updates do not emit silence completion again');
assert.equal(f.getMessage(), '', 'waiting updates do not begin messages');
assert.equal(f.sequence.beginControllerOnboarding(), true); assert.equal(f.sequence.beginControllerOnboarding(), false);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.CONTROLLER_ONBOARDING); assert.equal(f.getMessage(), VR_INTRO_COPY.en.opening[0]);
assert.equal(f.getRays(), 1); assert.equal(f.getInteractionEnables(), 1);
for (let i = 0; i < 10; i += 1) f.sequence.update(.01);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_PLAYER_PANEL_OPEN); assert.equal(f.getMessage(), VR_INTRO_COPY.en.panelPrompt);
f.sequence.update(1000); assert.equal(f.getMessage(), VR_INTRO_COPY.en.panelPrompt, 'Y prompt has no timeout');
f.panel.open = true; f.sequence.update(0); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_PLAYER_GUIDE_OPEN); assert.equal(f.getMessage(), '');
assert.equal(f.getPlayerOpenedGuide(), 1);
for (let i = 0; i < 5; i += 1) f.sequence.update(100);
assert.equal(f.getPlayerOpenedGuide(), 1, 'runtime wait does not emit guide opening again');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_PLAYER_GUIDE_OPEN);
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.continueControllerOnboarding(), false);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_CONTROLS_VIEW);
f.panel.section = 'other'; f.panel.view = 'DETAIL'; f.sequence.update(0); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_CONTROLS_VIEW);
f.panel.section = 'controls'; f.panel.view = 'DETAIL'; f.sequence.update(0);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_CONTROLS_VIEWED); assert.equal(f.getPlayerViewedControls(), 1);
for (let i = 0; i < 5; i += 1) f.sequence.update(100);
assert.equal(f.getPlayerViewedControls(), 1, 'runtime wait does not emit controls viewed again');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_CONTROLS_VIEWED, 'actor cannot advance to panel-close wait itself');
f.panel.open = false; f.sequence.update(0); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_CONTROLS_VIEWED, 'panel close is ignored before Runtime continuation');
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.continueControllerOnboarding(), false);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_PANEL_CLOSE);
f.panel.open = true; f.sequence.update(0); assert.equal(f.getPlayerClosedGuide(), 0, 'open panel does not emit closing');
f.panel.open = false; f.sequence.update(0);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_PLAYER_GUIDE_CLOSED); assert.equal(f.getPlayerClosedGuide(), 1);
for (let i = 0; i < 10; i += 1) f.sequence.update(.01);
assert.equal(f.getPlayerClosedGuide(), 1, 'runtime wait emits guide closing exactly once');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_PLAYER_GUIDE_CLOSED, 'actor cannot start pointer tutorial itself');
assert.equal(f.getOverride(), null, 'pointer tutorial remains stopped before Runtime continuation');
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.continueControllerOnboarding(), false);
for (let i = 0; i < 10; i += 1) f.sequence.update(.01);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_HOVER); assert.equal(f.getRays(), 1);
const messageBeforeHover = f.getMessage();
f.getOverride().onMonkeyHover();
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_MONKEY_HOVERED);
assert.equal(f.getMonkeyHovered(), 1); assert.equal(f.getMessage(), messageBeforeHover);
f.getOverride().onMonkeyHover(); f.sequence.update(100); assert.equal(f.getMonkeyHovered(), 1, 'runtime wait emits Monkey hover exactly once');
f.getOverride().onMonkeyPress(); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_MONKEY_HOVERED,
  'press during runtime wait is consumed without starting legacy flow');
assert.equal(f.getMessage(), messageBeforeHover); assert.notEqual(f.getMessage(), VR_INTRO_COPY.en.trigger);
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_TRIGGER);
assert.equal(f.getMessage(), VR_INTRO_COPY.en.trigger); assert.equal(f.sequence.continueControllerOnboarding(), false);
f.getOverride().onMonkeyPress();
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_MONKEY_TRIGGERED);
assert.equal(f.getMonkeyTriggered(), 1); assert.equal(f.getMessage(), VR_INTRO_COPY.en.trigger);
f.getOverride().onMonkeyPress(); f.sequence.update(100);
assert.equal(f.getMonkeyTriggered(), 1, 'runtime wait emits Monkey trigger exactly once');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_MONKEY_TRIGGERED);
assert.equal(f.getMessage(), VR_INTRO_COPY.en.trigger, 'seen flow remains stopped before Runtime continuation');
assert.equal(f.getOverride().options, undefined, 'invitation options are not installed before Runtime continuation');
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.continueControllerOnboarding(), false);
for (let i = 0; i < 8; i += 1) f.sequence.update(.01);
assert.equal(f.getMessage(), VR_INTRO_COPY.en.going, 'legacy seen sequence and invitation question remain unchanged');
f.getOverride().onSelect('go');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_INVITATION_SELECTED);
assert.deepEqual(f.getInvitationChoices(), [1]);
f.getOverride().onSelect('go'); assert.deepEqual(f.getInvitationChoices(), [1], 'runtime wait emits invitation choice exactly once');
assert.equal(f.sequence.continueInvitation(1), true);
assert.ok(f.sequence.getDebugSnapshot().monkeyRadius > 5, 'FOLLOWING has positive distance from radius 18 to threshold 5');
const stationaryStonePosition = f.monkeyStoneRoot.position.clone();
// Passing the three-metre grace point while actually following must not pause.
f.sequence.update(1.5);
f.head.copy(f.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0, 0, 2));
f.sequence.update(.1); assert.equal(f.sequence.isGuidePaused(), false);
// A lagging player pauses only beyond pauseDistance, then resumes below resumeDistance.
f.head.z = 40; const prePausePosition = f.monkeyMotionRoot.position.clone(); f.sequence.update(.1);
assert.deepEqual(f.getFollowPauseChanges(), [true]); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_FOLLOW_PAUSE_CHANGED);
assert.equal(f.sequence.isGuidePaused(), false); assert.notEqual(f.getMessage(), VR_INTRO_COPY.en.going);
assert.deepEqual(f.monkeyMotionRoot.position.toArray(), prePausePosition.toArray()); f.sequence.update(1); assert.deepEqual(f.getFollowPauseChanges(), [true]);
assert.equal(f.sequence.continueFollowPauseChanged(true), true); assert.equal(f.sequence.continueFollowPauseChanged(true), false);
assert.equal(f.sequence.isGuidePaused(), true); assert.equal(f.getMessage(), VR_INTRO_COPY.en.going);
const pausedFogRadius = f.fog.radius; f.sequence.update(2); assert.equal(f.fog.radius, pausedFogRadius, 'paused Monkey also pauses fog');
f.head.copy(f.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())); f.sequence.update(.1);
assert.deepEqual(f.getFollowPauseChanges(), [true, false]); assert.equal(f.sequence.isGuidePaused(), true); assert.equal(f.getMessage(), VR_INTRO_COPY.en.going);
const resumePosition = f.monkeyMotionRoot.position.clone(); assert.equal(f.sequence.continueFollowPauseChanged(false), true);
assert.equal(f.sequence.isGuidePaused(), false); assert.equal(f.getMessage(), ''); f.sequence.update(.1);
assert.notDeepEqual(f.monkeyMotionRoot.position.toArray(), resumePosition.toArray(), 'resume permits movement without an extra delayed frame');
assert.equal(f.sequence.getDebugSnapshot().followCheckResolved, true);
for (let i = 0; i < 20 && f.sequence.getState() === VR_INTRO_STATE.FOLLOWING; i += 1) {
  f.head.copy(f.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0, 0, 2));
  f.sequence.update(.5);
}
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_MONKEY_REACHED_THRESHOLD); assert.equal(f.sequence.isGuidePaused(), false);
assert.equal(f.getMonkeyReachedThreshold(), 1); assert.notEqual(f.getMessage(), VR_INTRO_COPY.en.threshold[0]);
const safeWaitPosition = f.monkeyMotionRoot.position.clone(); f.sequence.update(100);
assert.equal(f.getMonkeyReachedThreshold(), 1, 'safe wait does not emit threshold arrival again');
assert.deepEqual(f.monkeyMotionRoot.position.toArray(), safeWaitPosition.toArray(), 'safe wait stops Monkey movement');
const followFogSetRadiusCalls = f.fog.setRadiusCalls; f.sequence.update(100);
assert.equal(f.fog.setRadiusCalls, followFogSetRadiusCalls, 'safe wait does not apply the threshold presentation radius');
assert.equal(f.sequence.presentThresholdChoice(), true); assert.equal(f.sequence.getState(), VR_INTRO_STATE.THRESHOLD);
assert.equal(f.getMessage(), VR_INTRO_COPY.en.threshold[0]); assert.equal(f.fog.radius, 6); assert.equal(f.fog.setRadiusCalls, followFogSetRadiusCalls + 1);
assert.equal(f.sequence.presentThresholdChoice(), false, 'threshold presentation seam is exactly once');
f.sequence.update(100); assert.equal(f.fog.radius, 6, 'threshold wait holds radius 6');
assert.deepEqual(f.monkeyStoneRoot.position.toArray(), stationaryStonePosition.toArray(), 'stone is stationary during FOLLOWING');
assert.equal(f.glyphRing.visible, true); assert.equal(f.monkeyStoneRoot.visible, true, 'stone appears with ring reveal');
for (let i = 0; i < 12 && typeof f.getOverride()?.onSelect !== 'function'; i += 1) f.sequence.update(.01);
f.getOverride().onSelect('cross'); assert.equal(f.sequence.continueThresholdChoice(1), true); f.head.set(0, 1.7, 7.59); f.sequence.update(.1); assert.ok(f.fog.radius < 6); assert.equal(f.sequence.getDebugSnapshot().playerSafelyInside, false); assert.equal(f.getRadius(), 7.6);
f.head.z = 6.8; for (let i = 0; i < 28 && !f.sequence.getDebugSnapshot().monkeySettled; i += 1) f.sequence.update(.25);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.MONKEY_SETTLING); assert.equal(f.getPlayerEnteredRing(), 1); assert.equal(f.getMonkeySettled(), 1);
assert.equal(f.sequence.beginGlyphFreeExplore(), true); assert.equal(f.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE); assert.deepEqual(f.locomotion.lastOptions, { clamp: false });
assert.deepEqual(f.monkeyMotionRoot.position.toArray(), [0, 0, 0], 'Monkey settles at canonical final origin');
assert.equal(f.fog.radius, 0); assert.equal(f.fog.installed, false, 'fog is removed after P0 settling');
f.sequence.update(59.9); assert.equal(f.getGlyphHintTimeout(), 0, 'no timeout fact before 60 seconds');
f.sequence.update(.1); assert.equal(f.getGlyphHintTimeout(), 1, 'timeout emits its semantic fact at 60 seconds');
assert.equal(f.getAttention(), 0, 'timeout callback alone does not execute the hint');
f.sequence.update(100); assert.equal(f.getGlyphHintTimeout(), 1, 'timeout fact is emitted at most once');
assert.equal(f.sequence.getDebugSnapshot().glyphHintTriggered, true);
assert.equal(f.sequence.showGlyphHint(), true, 'Runtime continuation executes the existing hint');
assert.equal(f.sequence.showGlyphHint(), false, 'hint continuation is one-shot');
assert.equal(f.getAttention(), 1);
f.getOverride().onMonkeyPress(); f.sequence.update(.01); f.sequence.update(.01); assert.equal(f.getMessage(), VR_INTRO_COPY.en.glyphHint[1]);
assert.equal(f.sequence.notifyGlyphExploreSuccess(), true, 'a crystal still resolves discovery after the timeout hint');
assert.equal(f.getAttention(), 2); assert.equal(f.sequence.notifyGlyphExploreSuccess(), false, 'discovery is one-shot');
f.getOverride().onMonkeyPress();
for (let i = 0; i < 4; i += 1) f.sequence.update(.01);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.RELIQUARY_REVEAL);
let earlyReveal = 0;
const early = fixture({ onReliquaryReveal: (duration) => { earlyReveal = duration; } }); reachGlyphExplore(early);
early.sequence.update(30); assert.equal(early.sequence.notifyGlyphExploreSuccess(), true);
assert.equal(early.getAttention(), 1, 'early first crystal cancels the timeout and attracts attention once');
early.sequence.update(200); assert.equal(early.getAttention(), 1); assert.equal(early.getGlyphHintTimeout(), 0,
  'early discovery preserves its precedence over the delayed hint');
early.getOverride().onMonkeyPress(); for (let i = 0; i < 3; i += 1) early.sequence.update(.01);
assert.equal(earlyReveal, 3); assert.equal(early.sequence.getState(), VR_INTRO_STATE.RELIQUARY_REVEAL);
const thresholdBeyond = fixture(); reachThreshold(thresholdBeyond);
thresholdBeyond.getOverride().onSelect('beyond');
assert.equal(thresholdBeyond.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_THRESHOLD_SELECTED);
assert.deepEqual(thresholdBeyond.getThresholdChoices(), [2]);
assert.notEqual(thresholdBeyond.getMessage(), VR_INTRO_COPY.en.beyond[0], 'BEYOND copy waits for Runtime');
thresholdBeyond.getOverride().onSelect?.('beyond'); assert.deepEqual(thresholdBeyond.getThresholdChoices(), [2], 'safe wait emits once');
assert.equal(thresholdBeyond.sequence.continueThresholdChoice(2), true);
assert.equal(thresholdBeyond.sequence.getState(), VR_INTRO_STATE.THRESHOLD);
assert.equal(thresholdBeyond.getMessage(), VR_INTRO_COPY.en.beyond[0]);
assert.equal(thresholdBeyond.sequence.continueThresholdChoice(2), false);
for (let i = 0; i < 8 && typeof thresholdBeyond.getOverride()?.onSelect !== 'function'; i += 1) thresholdBeyond.sequence.update(.01);
thresholdBeyond.getOverride().onSelect('beyond'); assert.deepEqual(thresholdBeyond.getThresholdChoices(), [2, 2]);
assert.equal(thresholdBeyond.sequence.continueThresholdChoice(2), true);
for (let i = 0; i < 8 && typeof thresholdBeyond.getOverride()?.onSelect !== 'function'; i += 1) thresholdBeyond.sequence.update(.01);
thresholdBeyond.getOverride().onSelect('return'); assert.deepEqual(thresholdBeyond.getThresholdChoices(), [2, 2, 3]);
assert.equal(thresholdBeyond.getEndSessions(), 0); assert.equal(thresholdBeyond.sequence.continueThresholdChoice(3), true);
assert.equal(thresholdBeyond.sequence.getState(), VR_INTRO_STATE.ENDING); assert.equal(thresholdBeyond.getMessage(), VR_INTRO_COPY.en.returning[0]);
for (let i = 0; i < 8; i += 1) thresholdBeyond.sequence.update(.01);
assert.equal(thresholdBeyond.getEndSessions(), 1);
const thresholdCross = fixture(); reachThreshold(thresholdCross); const beforeCrossMessage = thresholdCross.getMessage();
thresholdCross.getOverride().onSelect('cross'); assert.deepEqual(thresholdCross.getThresholdChoices(), [1]);
assert.equal(thresholdCross.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_THRESHOLD_SELECTED); assert.equal(thresholdCross.getMessage(), beforeCrossMessage);
assert.equal(thresholdCross.sequence.continueThresholdChoice(1), true); assert.equal(thresholdCross.sequence.getState(), VR_INTRO_STATE.CROSSING); assert.equal(thresholdCross.getMessage(), '');
assert.equal(thresholdCross.sequence.continueThresholdChoice(1), false);
const lateEntry = fixture(); reachThreshold(lateEntry); lateEntry.getOverride().onSelect('cross'); assert.equal(lateEntry.sequence.continueThresholdChoice(1), true); lateEntry.head.set(0, 1.7, 7.8);
for (let i = 0; i < 40 && !lateEntry.sequence.getDebugSnapshot().monkeySettled; i += 1) lateEntry.sequence.update(.25);
assert.equal(lateEntry.sequence.getState(), VR_INTRO_STATE.MONKEY_SETTLING);
assert.equal(lateEntry.sequence.getDebugSnapshot().monkeySettled, true);
assert.equal(lateEntry.sequence.getDebugSnapshot().playerEnteredRing, false);
assert.notEqual(lateEntry.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE, 'gameplay waits for the physical ring crossing');
lateEntry.head.z = 7.5; lateEntry.sequence.update(0);
assert.equal(lateEntry.sequence.getDebugSnapshot().playerEnteredRing, true);
assert.equal(lateEntry.sequence.getDebugSnapshot().playerSafelyInside, false);
assert.equal(lateEntry.sequence.getState(), VR_INTRO_STATE.MONKEY_SETTLING, 'actor still waits after the second fact');
assert.equal(lateEntry.getMonkeySettled(), 1); assert.equal(lateEntry.getPlayerEnteredRing(), 1);
lateEntry.sequence.update(1); assert.equal(lateEntry.getMonkeySettled(), 1); assert.equal(lateEntry.getPlayerEnteredRing(), 1, 'semantic facts emit exactly once');
assert.equal(lateEntry.sequence.beginGlyphFreeExplore(), true); assert.equal(lateEntry.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE);
assert.equal(lateEntry.getRadius(), 7.6); assert.deepEqual(lateEntry.locomotion.lastOptions, { clamp: false });
assert.equal(lateEntry.getOverride(), null, 'narrative capture is cleared when free explore starts');
lateEntry.sequence.update(59.9); assert.equal(lateEntry.getGlyphHintTimeout(), 0, 'late-entry regression has no timeout before 60 seconds');
lateEntry.sequence.update(.1); assert.equal(lateEntry.getGlyphHintTimeout(), 1, 'late-entry regression emits exactly one timeout fact at 60 seconds');
assert.equal(lateEntry.getAttention(), 0, 'late-entry timeout still waits for Runtime');
assert.equal(lateEntry.sequence.showGlyphHint(), true); assert.equal(lateEntry.getAttention(), 1);
const hint = fixture(); hint.sequence.beginAfterXrCalibration(); hint.sequence.getDebugSnapshot(); // bypass choreography for timer is covered through public flow above
const bypassed = fixture({ bypass: true }); assert.equal(bypassed.sequence.getState(), VR_INTRO_STATE.BYPASSED); assert.equal(bypassed.fog.progress, 1); assert.equal(bypassed.monkeyStoneRoot.visible, true);
assert.equal(bypassed.getSilenceComplete(), 0); bypassed.sequence.update(100); assert.equal(bypassed.getSilenceComplete(), 0);
assert.equal(bypassed.getPlayerOpenedGuide(), 0, 'QA bypass does not synthesize guide opening');
assert.equal(bypassed.getPlayerViewedControls(), 0, 'QA bypass does not synthesize controls viewed');
assert.equal(bypassed.getPlayerClosedGuide(), 0, 'QA bypass does not synthesize guide closing');
assert.equal(bypassed.getMonkeyHovered(), 0, 'QA bypass does not synthesize Monkey hover');
assert.equal(bypassed.getMonkeyTriggered(), 0, 'QA bypass does not synthesize Monkey trigger');
f.sequence.reset(); assert.equal(f.sequence.getState(), VR_INTRO_STATE.XR_CALIBRATING); assert.equal(f.sequence.getDebugSnapshot().glyphExploreResolved, false);
f.sequence.beginAfterXrCalibration(); f.sequence.update(10); assert.equal(f.getRevealComplete(), 2, 'reset permits exactly one completion in the next run');
assert.equal(f.sequence.beginPostRevealSilence(), true, 'reset flow can resume through Runtime again');
f.sequence.update(2); assert.equal(f.getSilenceComplete(), 2, 'reset permits exactly one silence completion in the next run');
assert.equal(f.sequence.beginControllerOnboarding(), true, 'reset flow can resume controller onboarding through Runtime again');
console.log('VR intro sequence assertions passed');
