import assert from 'node:assert/strict';
import * as THREE from '../src/vendor/three.js';
import { createVrIntroSequence, VR_INTRO_COPY, VR_INTRO_STATE } from '../src/xr/guidance/createVrIntroSequence.js';

function fixture({ bypass = false, onReliquaryReveal = () => {} } = {}) {
  const platformRoot = new THREE.Group(); const progressFloor = { object: new THREE.Group() }; progressFloor.object.add(platformRoot);
  const monkeyMotionRoot = new THREE.Group(); monkeyMotionRoot.position.set(0, 1.25, -0.5); progressFloor.object.add(monkeyMotionRoot);
  const playerRig = new THREE.Group(); const head = new THREE.Vector3(0, 1.7, 20);
  const glyphRing = new THREE.Group(); const platformFixturesRoot = new THREE.Group(); const sector = new THREE.Group(); sector.userData.branchId = 'x'; progressFloor.object.add(sector);
  const monkeyStoneRoot = new THREE.Group(); progressFloor.object.add(monkeyStoneRoot);
  let message = ''; let override = null; let radius = 4; let attention = 0; let rays = 0; let revealComplete = 0; let silenceComplete = 0; let playerOpenedGuide = 0; let playerViewedControls = 0; let interactionEnables = 0;
  const panel = { open: false, view: 'MENU', section: null, isOpen() { return this.open; }, getViewState() { return this.view; }, getActiveSectionId() { return this.section; } };
  const fog = { progress: 0, radius: 20, installed: true, active: false, restart() { this.progress = 0; this.radius = 20; this.installed = true; this.active = false; }, start() { this.active = true; }, update(d) { if (!this.active) return; this.progress = Math.min(1, this.progress + d / 10); this.radius = 20 - 3 * this.progress; if (this.progress >= 1) this.active = false; }, setRadius(v) { this.radius = v; }, dispose() { this.installed = false; }, skipToEnd() { this.progress = 1; this.radius = 0; this.installed = false; }, getSnapshot() { return { progress: this.progress, radius: this.radius, installed: this.installed }; } };
  const monkeyGuide = { showMessage(v) { message = v; return { lineCount: v ? 1 : 0 }; }, setDialogueOverride(v) { override = v; }, setInteractionEnabled(value) { if (value) interactionEnables += 1; }, notifyAttention() { attention += 1; } };
  const locomotion = { reset() { radius = 4; }, setWalkRadius(v, options) { radius = v; this.lastOptions = options; } };
  const settings = { enabled: true, locale: 'en', introRevealDuration: 10, postRevealSilenceDuration: 2, insideSafeMargin: .75, glyphFreeExploreDuration: 60, guideSpeed: 2, guideTurnDuration: 1, followGraceDistance: 3, pauseDistance: 3.2, resumeDistance: 2.4, revealProgress: .72, messageDisplayDuration: 0, messageGapDuration: 0, questionGapDuration: 0 };
  const spatial = { entryDirection: { x: 0, y: 0, z: 1 }, playerStartRadius: 20, monkeyStartRadius: 18, monkeyFinal: { x: 0, y: 0, z: 0 }, ringRadius: 7.6, thresholdOutsideDistance: 1 };
  const sequence = createVrIntroSequence({ monkeyGuide, monkeyMotionRoot, monkeyVisualRoot: new THREE.Group(), monkeyStoneRoot, platformRoot, playerRig, playerGuidePanel: panel, fogReveal: fog, glyphRing, progressFloor, platformFixturesRoot, locomotion, spatial, settings, getHeadPosition: () => head.clone(), onOpeningRaysReady: () => { rays += 1; }, onIntroRevealComplete: () => { revealComplete += 1; }, onPostRevealSilenceComplete: () => { silenceComplete += 1; }, onPlayerOpenedGuide: () => { playerOpenedGuide += 1; }, onPlayerViewedControls: () => { playerViewedControls += 1; }, onReliquaryReveal, bypass });
  return { sequence, monkeyMotionRoot, monkeyStoneRoot, glyphRing, head, panel, fog, locomotion, getMessage: () => message, getOverride: () => override, getRadius: () => radius, getAttention: () => attention, getRays: () => rays, getRevealComplete: () => revealComplete, getSilenceComplete: () => silenceComplete, getPlayerOpenedGuide: () => playerOpenedGuide, getPlayerViewedControls: () => playerViewedControls, getInteractionEnables: () => interactionEnables };
}
function reachThreshold(value) {
  value.sequence.beginAfterXrCalibration(); value.sequence.update(10); assert.equal(value.sequence.beginPostRevealSilence(), true); value.sequence.update(2); assert.equal(value.sequence.beginControllerOnboarding(), true);
  for (let i = 0; i < 10; i += 1) value.sequence.update(.01);
  value.panel.open = true; value.sequence.update(0); assert.equal(value.sequence.continueControllerOnboarding(), true); value.panel.section = 'controls'; value.panel.view = 'DETAIL'; value.sequence.update(0);
  assert.equal(value.sequence.continueControllerOnboarding(), true);
  value.panel.open = false; value.sequence.update(0); for (let i = 0; i < 10; i += 1) value.sequence.update(.01);
  value.getOverride().onMonkeyHover(); value.getOverride().onMonkeyPress(); for (let i = 0; i < 8; i += 1) value.sequence.update(.01);
  value.sequence.chooseInvitation('go');
  for (let i = 0; i < 30 && value.sequence.getState() === VR_INTRO_STATE.FOLLOWING; i += 1) {
    value.head.copy(value.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())); value.sequence.update(.5);
  }
  assert.equal(value.sequence.getState(), VR_INTRO_STATE.THRESHOLD);
}
function reachGlyphExplore(value) {
  reachThreshold(value);
  value.sequence.chooseThreshold('cross'); value.head.set(0, 1.7, 6.8);
  for (let i = 0; i < 30 && value.sequence.getState() !== VR_INTRO_STATE.GLYPH_FREE_EXPLORE; i += 1) value.sequence.update(.25);
  assert.equal(value.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE);
}
assert.deepEqual(VR_INTRO_COPY.pl.opening, ['Dobrze.', 'Masz ręce.', 'Sprawdźmy tylko, gdzie co masz.']);
assert.equal(VR_INTRO_COPY.pl.panelPrompt, 'Naciśnij Y, żeby wejść do menu.');
assert.equal(VR_INTRO_COPY.en.panelPrompt, 'Press Y to open the menu.');
const f = fixture(); assert.equal(f.sequence.getState(), VR_INTRO_STATE.XR_CALIBRATING);
assert.equal(f.sequence.continueControllerOnboarding(), false, 'runtime continuation rejects the wrong actor state');
assert.equal(f.monkeyStoneRoot.visible, true); assert.equal(f.glyphRing.visible, true); assert.equal(f.fog.radius, 20);
f.sequence.beginAfterXrCalibration();
assert.ok(Math.abs(f.sequence.getDebugSnapshot().monkeyRadius - 18) < 1e-6);
f.head.x = 5; f.sequence.reset(); f.sequence.beginAfterXrCalibration();
assert.ok(Math.abs(f.sequence.getDebugSnapshot().monkeyRadius - 18) < 1e-6, 'physical head offset never changes Monkey start');
f.head.x = 0;
f.sequence.update(5); assert.equal(f.sequence.getState(), VR_INTRO_STATE.FOG_REVEAL); assert.equal(f.fog.radius, 18.5);
f.sequence.update(5); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_REVEAL); assert.equal(f.fog.radius, 17); assert.equal(f.getMessage(), '');
assert.equal(f.getRevealComplete(), 1, 'fog completion emits exactly once');
f.sequence.update(100); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_REVEAL, 'silence does not begin without Runtime');
assert.equal(f.getRevealComplete(), 1, 'waiting updates do not emit completion again');
assert.equal(f.sequence.beginControllerOnboarding(), false, 'onboarding cannot begin before silence completion');
assert.equal(f.sequence.beginPostRevealSilence(), true); assert.equal(f.sequence.beginPostRevealSilence(), false);
f.sequence.update(1.99); assert.equal(f.getMessage(), ''); assert.equal(f.getSilenceComplete(), 0);
f.sequence.update(.01); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_POST_REVEAL_SILENCE);
assert.equal(f.getSilenceComplete(), 1); assert.equal(f.getMessage(), ''); assert.equal(f.getRays(), 0); assert.equal(f.getInteractionEnables(), 0);
for (let i = 0; i < 20; i += 1) f.sequence.update(100);
assert.equal(f.getSilenceComplete(), 1, 'waiting updates do not emit silence completion again');
assert.equal(f.getMessage(), '', 'waiting updates do not begin messages');
assert.equal(f.sequence.beginControllerOnboarding(), true); assert.equal(f.sequence.beginControllerOnboarding(), false);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.CONTROLLER_ONBOARDING); assert.equal(f.getMessage(), VR_INTRO_COPY.en.opening[0]);
assert.equal(f.getRays(), 1); assert.equal(f.getInteractionEnables(), 1);
for (let i = 0; i < 10; i += 1) f.sequence.update(.01);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_PLAYER_PANEL_OPEN); assert.equal(f.getMessage(), VR_INTRO_COPY.en.panelPrompt);
f.sequence.update(1000); assert.equal(f.getMessage(), VR_INTRO_COPY.en.panelPrompt, 'Y prompt has no timeout');
f.panel.open = true; f.sequence.update(0); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_PLAYER_GUIDE_OPEN); assert.equal(f.getMessage(), '');
assert.equal(f.getPlayerOpenedGuide(), 1);
for (let i = 0; i < 5; i += 1) f.sequence.update(100);
assert.equal(f.getPlayerOpenedGuide(), 1, 'runtime wait does not emit guide opening again');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_PLAYER_GUIDE_OPEN);
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.continueControllerOnboarding(), false);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_CONTROLS_VIEW);
f.panel.section = 'other'; f.panel.view = 'DETAIL'; f.sequence.update(0); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_CONTROLS_VIEW);
f.panel.section = 'controls'; f.panel.view = 'DETAIL'; f.sequence.update(0);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_CONTROLS_VIEWED); assert.equal(f.getPlayerViewedControls(), 1);
for (let i = 0; i < 5; i += 1) f.sequence.update(100);
assert.equal(f.getPlayerViewedControls(), 1, 'runtime wait does not emit controls viewed again');
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_CONTROLS_VIEWED, 'actor cannot advance to panel-close wait itself');
f.panel.open = false; f.sequence.update(0); assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_RUNTIME_AFTER_CONTROLS_VIEWED, 'panel close is ignored before Runtime continuation');
assert.equal(f.sequence.continueControllerOnboarding(), true); assert.equal(f.sequence.continueControllerOnboarding(), false);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_PANEL_CLOSE); f.sequence.update(0); for (let i = 0; i < 10; i += 1) f.sequence.update(.01);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.WAIT_HOVER); assert.equal(f.getRays(), 1);
f.getOverride().onMonkeyHover(); f.getOverride().onMonkeyPress(); for (let i = 0; i < 8; i += 1) f.sequence.update(.01); f.sequence.chooseInvitation('go');
assert.ok(f.sequence.getDebugSnapshot().monkeyRadius > 5, 'FOLLOWING has positive distance from radius 18 to threshold 5');
const stationaryStonePosition = f.monkeyStoneRoot.position.clone();
// Passing the three-metre grace point while actually following must not pause.
f.sequence.update(1.5);
f.head.copy(f.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0, 0, 2));
f.sequence.update(.1); assert.equal(f.sequence.isGuidePaused(), false);
// A lagging player pauses only beyond pauseDistance, then resumes below resumeDistance.
f.head.z = 40; f.sequence.update(.1); assert.equal(f.sequence.isGuidePaused(), true);
const pausedFogRadius = f.fog.radius; f.sequence.update(2); assert.equal(f.fog.radius, pausedFogRadius, 'paused Monkey also pauses fog');
f.head.copy(f.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())); f.sequence.update(.1); assert.equal(f.sequence.getDebugSnapshot().followCheckResolved, true);
for (let i = 0; i < 20 && f.sequence.getState() === VR_INTRO_STATE.FOLLOWING; i += 1) {
  f.head.copy(f.monkeyMotionRoot.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(0, 0, 2));
  f.sequence.update(.5);
}
assert.equal(f.sequence.getState(), VR_INTRO_STATE.THRESHOLD); assert.equal(f.sequence.isGuidePaused(), false);
assert.equal(f.fog.radius, 6); f.sequence.update(100); assert.equal(f.fog.radius, 6, 'threshold wait holds radius 6');
assert.deepEqual(f.monkeyStoneRoot.position.toArray(), stationaryStonePosition.toArray(), 'stone is stationary during FOLLOWING');
assert.equal(f.glyphRing.visible, true); assert.equal(f.monkeyStoneRoot.visible, true, 'stone appears with ring reveal');
f.sequence.chooseThreshold('cross'); f.head.set(0, 1.7, 7.59); f.sequence.update(.1); assert.ok(f.fog.radius < 6); assert.equal(f.sequence.getDebugSnapshot().playerSafelyInside, false); assert.equal(f.getRadius(), 7.6);
f.head.z = 6.8; for (let i = 0; i < 28 && f.sequence.getState() !== VR_INTRO_STATE.GLYPH_FREE_EXPLORE; i += 1) f.sequence.update(.25);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE); assert.deepEqual(f.locomotion.lastOptions, { clamp: false });
assert.deepEqual(f.monkeyMotionRoot.position.toArray(), [0, 0, 0], 'Monkey settles at canonical final origin');
assert.equal(f.fog.radius, 0); assert.equal(f.fog.installed, false, 'fog is removed after P0 settling');
f.sequence.update(59.9); assert.equal(f.getAttention(), 0, 'no hint before 60 seconds');
f.sequence.update(.1); assert.equal(f.getAttention(), 1, 'timeout arms Monkey hint at 60 seconds');
assert.equal(f.sequence.getDebugSnapshot().glyphHintTriggered, true);
f.getOverride().onMonkeyPress(); f.sequence.update(.01); f.sequence.update(.01); assert.equal(f.getMessage(), VR_INTRO_COPY.en.glyphHint[1]);
assert.equal(f.sequence.notifyGlyphExploreSuccess(), true, 'a crystal still resolves discovery after the timeout hint');
assert.equal(f.getAttention(), 2); assert.equal(f.sequence.notifyGlyphExploreSuccess(), false, 'discovery is one-shot');
f.getOverride().onMonkeyPress();
for (let i = 0; i < 4; i += 1) f.sequence.update(.01);
assert.equal(f.sequence.getState(), VR_INTRO_STATE.RELIQUARY_REVEAL);
let earlyReveal = 0;
const early = fixture({ onReliquaryReveal: (duration) => { earlyReveal = duration; } }); reachGlyphExplore(early);
early.sequence.update(30); assert.equal(early.sequence.notifyGlyphExploreSuccess(), true);
assert.equal(early.getAttention(), 1, 'early first crystal cancels the timeout and attracts attention once');
early.sequence.update(200); assert.equal(early.getAttention(), 1);
early.getOverride().onMonkeyPress(); for (let i = 0; i < 3; i += 1) early.sequence.update(.01);
assert.equal(earlyReveal, 3); assert.equal(early.sequence.getState(), VR_INTRO_STATE.RELIQUARY_REVEAL);
const lateEntry = fixture(); reachThreshold(lateEntry); lateEntry.sequence.chooseThreshold('cross'); lateEntry.head.set(0, 1.7, 7.8);
for (let i = 0; i < 40 && !lateEntry.sequence.getDebugSnapshot().monkeySettled; i += 1) lateEntry.sequence.update(.25);
assert.equal(lateEntry.sequence.getState(), VR_INTRO_STATE.MONKEY_SETTLING);
assert.equal(lateEntry.sequence.getDebugSnapshot().monkeySettled, true);
assert.equal(lateEntry.sequence.getDebugSnapshot().playerEnteredRing, false);
assert.notEqual(lateEntry.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE, 'gameplay waits for the physical ring crossing');
lateEntry.head.z = 7.5; lateEntry.sequence.update(0);
assert.equal(lateEntry.sequence.getDebugSnapshot().playerEnteredRing, true);
assert.equal(lateEntry.sequence.getDebugSnapshot().playerSafelyInside, false);
assert.equal(lateEntry.sequence.getState(), VR_INTRO_STATE.GLYPH_FREE_EXPLORE);
assert.equal(lateEntry.getRadius(), 7.6); assert.deepEqual(lateEntry.locomotion.lastOptions, { clamp: false });
assert.equal(lateEntry.getOverride(), null, 'narrative capture is cleared when free explore starts');
lateEntry.sequence.update(59.9); assert.equal(lateEntry.getAttention(), 0, 'late-entry regression has no hint before 60 seconds');
lateEntry.sequence.update(.1); assert.equal(lateEntry.getAttention(), 1, 'late-entry regression arms exactly one hint at 60 seconds');
const hint = fixture(); hint.sequence.beginAfterXrCalibration(); hint.sequence.getDebugSnapshot(); // bypass choreography for timer is covered through public flow above
const bypassed = fixture({ bypass: true }); assert.equal(bypassed.sequence.getState(), VR_INTRO_STATE.BYPASSED); assert.equal(bypassed.fog.progress, 1); assert.equal(bypassed.monkeyStoneRoot.visible, true);
assert.equal(bypassed.getSilenceComplete(), 0); bypassed.sequence.update(100); assert.equal(bypassed.getSilenceComplete(), 0);
assert.equal(bypassed.getPlayerOpenedGuide(), 0, 'QA bypass does not synthesize guide opening');
assert.equal(bypassed.getPlayerViewedControls(), 0, 'QA bypass does not synthesize controls viewed');
f.sequence.reset(); assert.equal(f.sequence.getState(), VR_INTRO_STATE.XR_CALIBRATING); assert.equal(f.sequence.getDebugSnapshot().glyphExploreResolved, false);
f.sequence.beginAfterXrCalibration(); f.sequence.update(10); assert.equal(f.getRevealComplete(), 2, 'reset permits exactly one completion in the next run');
assert.equal(f.sequence.beginPostRevealSilence(), true, 'reset flow can resume through Runtime again');
f.sequence.update(2); assert.equal(f.getSilenceComplete(), 2, 'reset permits exactly one silence completion in the next run');
assert.equal(f.sequence.beginControllerOnboarding(), true, 'reset flow can resume controller onboarding through Runtime again');
console.log('VR intro sequence assertions passed');
