import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import * as THREE from '../src/vendor/three.js';
import { ASSET_STAGES, getPreloadAssets } from '../src/assets/assetManifest.js';
import { createVrReliquaryActivateButton } from '../src/xr/createVrReliquaryActivateButton.js';

const asset = getPreloadAssets([ASSET_STAGES.DEFERRED_WARM]).find(({ id }) => id === 'vr-crystal-reliquary-button-activate-model');
assert.deepEqual({ label: asset.label, path: asset.path, type: asset.type }, { label: 'VR crystal reliquary activate button', path: '/glb/portal_crystal_reliquary_button_activate.glb', type: 'model' });
const runtime = await readFile(new URL('../src/experienceVr.js', import.meta.url), 'utf8');
assert.match(runtime, /getGltf\('vr-crystal-reliquary-button-activate-model'\)/);
assert.match(runtime, /attachAuthoredCompanion\(activateButtonModel, settings\.reliquary\.activateButton\)/);

const scene = new THREE.Scene();
const model = new THREE.Group();
const root = new THREE.Group(); root.name = 'RELIQUARY_ACTIVATE_BUTTON_ROOT'; model.add(root);
const visual = new THREE.Mesh(new THREE.BoxGeometry(0.2, 0.2, 0.2), new THREE.MeshStandardMaterial({ emissive: 0xffffff, emissiveIntensity: 7 }));
visual.name = 'RELIQUARY_ACTIVATE_BUTTON_FRONT'; root.add(visual);
const sourceMaterial = visual.material;
const trigger = new THREE.Mesh(new THREE.BoxGeometry(0.4, 0.4, 0.1), new THREE.MeshBasicMaterial());
trigger.name = 'RELIQUARY_ACTIVATE_TRIGGER_SURFACE'; trigger.position.z = -1;
trigger.userData = { reliquary_role: 'crystal_activate_trigger', reliquary_button_id: 'activate', reliquary_action: 'activate_inserted_crystal' };
model.add(trigger); scene.add(model);
const controller = new THREE.Group(); scene.add(controller);
const record = { controller, currentRayLength: 2, currentHit: { glyph: true }, currentCrystalHit: { crystal: true } };
let eligible = false; let activations = 0;
const clip = new THREE.AnimationClip('Relic_Reliquary_ActivateButton_Press', 1, [new THREE.NumberKeyframeTrack(`${root.name}.position[y]`, [0, 1], [0, -0.1])]);
scene.updateMatrixWorld(true);
const button = createVrReliquaryActivateButton({ buttonModel: model, animations: [clip], reliquary: { object: model }, controllers: [record], settings: { enabled: true, rayMaxDistance: 3 }, canActivate: () => eligible, onActivate: () => { activations += 1; return true; } });
assert.equal(button.trigger, trigger);
assert.equal(trigger.visible, true);
assert.equal(trigger.material.transparent, true); assert.equal(trigger.material.opacity, 0); assert.equal(trigger.material.depthWrite, false); assert.equal(trigger.material.colorWrite, false);
assert.notEqual(visual.material, sourceMaterial); assert.equal(visual.material.emissiveMap, sourceMaterial.emissiveMap);
button.update(0); assert.equal(visual.material.emissiveIntensity, 0); assert.deepEqual(record.currentHit, { glyph: true }); assert.deepEqual(record.currentCrystalHit, { crystal: true });
controller.dispatchEvent({ type: 'selectstart' }); assert.equal(activations, 0);
eligible = true; button.update(0); assert.equal(button.hovered, true); assert.equal(visual.material.emissiveIntensity, 1);
controller.rotation.y = Math.PI; button.update(0); assert.equal(button.hovered, false); assert.equal(visual.material.emissiveIntensity, 0);
controller.rotation.y = 0; scene.updateMatrixWorld(true); button.update(0); controller.dispatchEvent({ type: 'selectstart' });
assert.equal(activations, 1); assert.equal(button.state, 'active'); assert.equal(visual.material.emissiveIntensity, 5);
assert.equal(button.action.loop, THREE.LoopOnce); assert.equal(button.action.clampWhenFinished, true); assert.equal(button.action.isRunning(), true);
button.update(2); assert.ok(root.position.y < -0.09); controller.dispatchEvent({ type: 'selectstart' }); assert.equal(activations, 1);
button.reset(); assert.equal(button.state, 'idle'); assert.equal(button.hovered, false); assert.equal(visual.material.emissiveIntensity, 0); assert.ok(Math.abs(root.position.y) < 1e-8);
button.reset(); button.dispose(); button.dispose();
console.log('VR reliquary activate button assertions passed');
